### PR TITLE
Add styles generated by JSS to jest snapshots

### PR DESCRIPTION
**Pull request by GuilleDF**
This adds styles to the snapshots generated by jest, similar to projects like: https://github.com/styled-components/jest-styled-components. Additionally, this changes all of the dynamic class names generated by JSS to something predictable, to prevent false positives (this behaviour was already present, but it didn’t seem to work).

An example of how the snapshots look:

image

### CODE REVIEW

**Comment by kof** [comment]
Thanks for putting this together @GuilleDF, I am hoping @vovacodes could review/merge/release the changes

Curious - is taxfix using JSS? If yes in what products?

**Comment by GuilleDF** [comment]
@kof
Happy to help! 😃

We're not using JSS directly, but we are using https://github.com/mui-org/material-ui , which provides a styling solution based on JSS

**Comment by GuilleDF** [comment]
Hi @kof & @vovacodes, any update on this? 😇

**Review by vovacodes — APPROVED** [review]
It's a terrific effort, thanks for the contribution! BTW I'm not using JSS at my current project so it might be hard for me to maintain this package properly, @GuilleDF let me know if you're interested in maintaining it, I'll gladly give you all the permission

**Comment by GuilleDF** [comment]
@vovacodes That sounds good, I'd be happy to maintain it! 😃

**Comment by vovacodes** [comment]
@GuilleDF Sweet! I made you a maintainer on guthub, do you mind giving me your npm username so I can give you publishing rights

**Comment by GuilleDF** [comment]
@vovacodes Yeah, it's `gdefermin` 😄

**Comment by vovacodes** [comment]
Done, feel free to publish a new version, this should also verify that you have all the permissions set up.

**Comment by GuilleDF** [comment]
Hmm, strange, I'm getting a 403 when I try to publish, but I do see the package under my list of packages:
https://www.npmjs.com/settings/gdefermin/packages

**Comment by GuilleDF** [comment]
It wasn't working for a second, but now it is -- published correctly! Thanks! 😃

**Pull request merged**
